export type WordType = 'noun' | 'verb' | 'adjective' | 'adverb';

export interface Flashcard {
  id: string;
  italian: string;
  english: string;
  type: WordType;
  gender?: 'masculine' | 'feminine';
  example?: string;
  exampleTranslation?: string;
  italian_alias?: string;
}

export interface Conjugation {
  io: string;
  tu: string;
  lui: string;
  noi: string;
  voi: string;
  loro: string;
}

export type TenseId =
  | 'presente'
  | 'passato_prossimo'
  | 'imperfetto'
  | 'futuro_semplice'
  | 'condizionale_presente'
  | 'congiuntivo_presente'
  | 'imperativo';

export interface Verb {
  id: string;
  infinitive: string;
  english: string;
  type: 'regular-are' | 'regular-ere' | 'regular-ire' | 'irregular';
  reflexive?: boolean;
  auxiliary?: 'avere' | 'essere';
  tenses: Partial<Record<TenseId, Conjugation>>;
}

export interface TenseInfo {
  id: TenseId;
  name: string;
  italianName: string;
  when: string;
  trigger?: string;
  examples: { italian: string; english: string }[];
  formation?: string;
}

export const FLASHCARDS: Flashcard[] = [
  // Nouns
  { id: 'n1', italian: 'la casa', english: 'house / home', type: 'noun', gender: 'feminine', example: 'Abito in una bella casa.', exampleTranslation: 'I live in a beautiful house.' },
  { id: 'n2', italian: 'il libro', english: 'book', type: 'noun', gender: 'masculine', example: 'Sto leggendo un libro interessante.', exampleTranslation: 'I am reading an interesting book.' },
  { id: 'n3', italian: 'l\'acqua', english: 'water', type: 'noun', gender: 'feminine', example: 'Bevo molta acqua ogni giorno.', exampleTranslation: 'I drink a lot of water every day.' },
  { id: 'n4', italian: 'il cibo', english: 'food', type: 'noun', gender: 'masculine', example: 'Il cibo italiano è delizioso.', exampleTranslation: 'Italian food is delicious.' },
  { id: 'n5', italian: 'il tempo', english: 'time / weather', type: 'noun', gender: 'masculine', example: 'Non ho tempo oggi.', exampleTranslation: 'I don\'t have time today.' },
  { id: 'n6', italian: 'il giorno', english: 'day', type: 'noun', gender: 'masculine', example: 'Buon giorno!', exampleTranslation: 'Good day!' },
  { id: 'n7', italian: 'la notte', english: 'night', type: 'noun', gender: 'feminine', example: 'La notte è tranquilla.', exampleTranslation: 'The night is quiet.' },
  { id: 'n8', italian: 'il lavoro', english: 'work / job', type: 'noun', gender: 'masculine', example: 'Il mio lavoro è molto interessante.', exampleTranslation: 'My work is very interesting.' },
  { id: 'n9', italian: 'l\'amore', english: 'love', type: 'noun', gender: 'masculine', example: 'L\'amore è la cosa più importante.', exampleTranslation: 'Love is the most important thing.' },
  { id: 'n10', italian: 'la vita', english: 'life', type: 'noun', gender: 'feminine', example: 'La vita è bella.', exampleTranslation: 'Life is beautiful.' },
  { id: 'n11', italian: 'l\'amico', english: 'friend (male)', type: 'noun', gender: 'masculine', example: 'Il mio amico si chiama Marco.', exampleTranslation: 'My friend is named Marco.' },
  { id: 'n12', italian: 'la famiglia', english: 'family', type: 'noun', gender: 'feminine', example: 'La mia famiglia è grande.', exampleTranslation: 'My family is large.' },
  { id: 'n13', italian: 'la città', english: 'city', type: 'noun', gender: 'feminine', example: 'Roma è una città bellissima.', exampleTranslation: 'Rome is a very beautiful city.' },
  { id: 'n14', italian: 'il mare', english: 'sea', type: 'noun', gender: 'masculine', example: 'Andiamo al mare in estate.', exampleTranslation: 'We go to the sea in summer.' },
  { id: 'n15', italian: 'il pane', english: 'bread', type: 'noun', gender: 'masculine', example: 'Mi piace il pane fresco.', exampleTranslation: 'I like fresh bread.' },
  { id: 'n16', italian: 'la strada', english: 'street / road', type: 'noun', gender: 'feminine', example: 'Questa strada è molto lunga.', exampleTranslation: 'This road is very long.' },
  { id: 'n17', italian: 'la musica', english: 'music', type: 'noun', gender: 'feminine', example: 'Ascolto la musica ogni sera.', exampleTranslation: 'I listen to music every evening.' },
  { id: 'n18', italian: 'il vino', english: 'wine', type: 'noun', gender: 'masculine', example: 'Questo vino è eccellente.', exampleTranslation: 'This wine is excellent.' },
  { id: 'n19', italian: 'il sole', english: 'sun', type: 'noun', gender: 'masculine', example: 'Il sole splende oggi.', exampleTranslation: 'The sun is shining today.' },
  { id: 'n20', italian: 'la luna', english: 'moon', type: 'noun', gender: 'feminine', example: 'La luna è piena stasera.', exampleTranslation: 'The moon is full tonight.' },
  { id: 'n21', italian: 'la terra', english: 'earth / land', type: 'noun', gender: 'feminine', example: 'La terra è umida.', exampleTranslation: 'The earth is damp.' },
  { id: 'n22', italian: 'il cielo', english: 'sky', type: 'noun', gender: 'masculine', example: 'Il cielo è azzurro.', exampleTranslation: 'The sky is blue.' },
  { id: 'n23', italian: 'la mano', english: 'hand', type: 'noun', gender: 'feminine', example: 'Dammi la mano.', exampleTranslation: 'Give me your hand.' },
  { id: 'n24', italian: 'il piede', english: 'foot', type: 'noun', gender: 'masculine', example: 'Mi fa male il piede.', exampleTranslation: 'My foot hurts.' },
  { id: 'n25', italian: 'la testa', english: 'head', type: 'noun', gender: 'feminine', example: 'Ho mal di testa.', exampleTranslation: 'I have a headache.' },
  { id: 'n26', italian: 'il cuore', english: 'heart', type: 'noun', gender: 'masculine', example: 'Il cuore batte forte.', exampleTranslation: 'The heart beats fast.' },
  { id: 'n27', italian: 'la macchina', english: 'car', type: 'noun', gender: 'feminine', example: 'Guido la mia macchina.', exampleTranslation: 'I drive my car.' },
  { id: 'n28', italian: 'il treno', english: 'train', type: 'noun', gender: 'masculine', example: 'Il treno parte alle otto.', exampleTranslation: 'The train leaves at eight.' },
  { id: 'n29', italian: 'la scuola', english: 'school', type: 'noun', gender: 'feminine', example: 'Vado a scuola ogni giorno.', exampleTranslation: 'I go to school every day.' },
  { id: 'n30', italian: 'il professore', english: 'teacher', type: 'noun', gender: 'masculine', example: 'Il professore spiega bene.', exampleTranslation: 'The teacher explains well.' },
  { id: 'n31', italian: 'la tavola', english: 'table (set)', type: 'noun', gender: 'feminine', example: 'La tavola è apparecchiata.', exampleTranslation: 'The table is set.' },
  { id: 'n32', italian: 'la sedia', english: 'chair', type: 'noun', gender: 'feminine', example: 'Siediti sulla sedia.', exampleTranslation: 'Sit on the chair.' },
  { id: 'n33', italian: 'la finestra', english: 'window', type: 'noun', gender: 'feminine', example: 'Apri la finestra, per favore.', exampleTranslation: 'Open the window, please.' },
  { id: 'n34', italian: 'il giornale', english: 'newspaper', type: 'noun', gender: 'masculine', example: 'Leggo il giornale ogni mattina.', exampleTranslation: 'I read the newspaper every morning.' },
  { id: 'n35', italian: 'la borsa', english: 'bag / purse', type: 'noun', gender: 'feminine', example: 'Ho dimenticato la borsa.', exampleTranslation: 'I forgot my bag.' },
  { id: 'n36', italian: 'la chiave', english: 'key', type: 'noun', gender: 'feminine', example: 'Dov\'è la chiave di casa?', exampleTranslation: 'Where is the house key?' },
  { id: 'n37', italian: 'il telefono', english: 'phone', type: 'noun', gender: 'masculine', example: 'Il mio telefono è scarico.', exampleTranslation: 'My phone is out of battery.' },
  { id: 'n38', italian: 'la piazza', english: 'square', type: 'noun', gender: 'feminine', example: 'Ci vediamo in piazza.', exampleTranslation: 'Let\'s meet in the square.' },
  { id: 'n39', italian: 'il parco', english: 'park', type: 'noun', gender: 'masculine', example: 'Corro nel parco.', exampleTranslation: 'I run in the park.' },
  { id: 'n40', italian: 'la valigia', english: 'suitcase', type: 'noun', gender: 'feminine', example: 'La mia valigia è pesante.', exampleTranslation: 'My suitcase is heavy.' },
  { id: 'n41', italian: 'la cucina', english: 'kitchen', type: 'noun', gender: 'feminine', example: 'La cucina è molto grande.', exampleTranslation: 'The kitchen is very large.' },
  { id: 'n42', italian: 'il letto', english: 'bed', type: 'noun', gender: 'masculine', example: 'Il letto è molto comodo.', exampleTranslation: 'The bed is very comfortable.' },
  { id: 'n43', italian: 'il cane', english: 'dog', type: 'noun', gender: 'masculine', example: 'Ho un cane piccolo.', exampleTranslation: 'I have a small dog.' },
  { id: 'n44', italian: 'il gatto', english: 'cat', type: 'noun', gender: 'masculine', example: 'Il gatto dorme tutto il giorno.', exampleTranslation: 'The cat sleeps all day.' },
  { id: 'n45', italian: 'l\'uccello', english: 'bird', type: 'noun', gender: 'masculine', example: 'L\'uccello canta al mattino.', exampleTranslation: 'The bird sings in the morning.' },
  { id: 'n46', italian: 'il pesce', english: 'fish', type: 'noun', gender: 'masculine', example: 'Il pesce è delizioso.', exampleTranslation: 'The fish is delicious.' },
  { id: 'n47', italian: 'la mela', english: 'apple', type: 'noun', gender: 'feminine', example: 'Mi piace una mela rossa.', exampleTranslation: 'I like a red apple.' },
  { id: 'n48', italian: 'la banana', english: 'banana', type: 'noun', gender: 'feminine', example: 'Mangio una banana al mattino.', exampleTranslation: 'I eat a banana in the morning.' },
  { id: 'n49', italian: 'l\'arancia', english: 'orange', type: 'noun', gender: 'feminine', example: 'L\'arancia è succosa.', exampleTranslation: 'The orange is juicy.' },
  { id: 'n50', italian: 'la fragola', english: 'strawberry', type: 'noun', gender: 'feminine', example: 'Le fragole sono dolci.', exampleTranslation: 'Strawberries are sweet.' },
  { id: 'n51', italian: 'il formaggio', english: 'cheese', type: 'noun', gender: 'masculine', example: 'Mi piace il formaggio italiano.', exampleTranslation: 'I like Italian cheese.' },
  { id: 'n52', italian: 'il latte', english: 'milk', type: 'noun', gender: 'masculine', example: 'Bevo il latte a colazione.', exampleTranslation: 'I drink milk for breakfast.' },
  { id: 'n53', italian: 'il burro', english: 'butter', type: 'noun', gender: 'masculine', example: 'Metto il burro sul pane.', exampleTranslation: 'I put butter on bread.' },
  { id: 'n54', italian: 'l\'uovo', english: 'egg', type: 'noun', gender: 'masculine', example: 'Mangio un uovo a colazione.', exampleTranslation: 'I eat an egg for breakfast.' },
  { id: 'n55', italian: 'la carne', english: 'meat', type: 'noun', gender: 'feminine', example: 'La carne è buona.', exampleTranslation: 'The meat is good.' },
  { id: 'n56', italian: 'il pollo', english: 'chicken', type: 'noun', gender: 'masculine', example: 'Cucino il pollo per cena.', exampleTranslation: 'I cook chicken for dinner.' },
  { id: 'n57', italian: 'la verdura', english: 'vegetable', type: 'noun', gender: 'feminine', example: 'Mangio molta verdura.', exampleTranslation: 'I eat a lot of vegetables.' },
  { id: 'n58', italian: 'il riso', english: 'rice', type: 'noun', gender: 'masculine', example: 'Il riso è delizioso.', exampleTranslation: 'The rice is delicious.' },
  { id: 'n59', italian: 'la pasta', english: 'pasta', type: 'noun', gender: 'feminine', example: 'Amo la pasta italiana.', exampleTranslation: 'I love Italian pasta.' },
  { id: 'n60', italian: 'la birra', english: 'beer', type: 'noun', gender: 'feminine', example: 'Mi piace la birra fredda.', exampleTranslation: 'I like cold beer.' },
  { id: 'n61', italian: 'il caffè', english: 'coffee', type: 'noun', gender: 'masculine', example: 'Bevo il caffè ogni mattina.', exampleTranslation: 'I drink coffee every morning.' },
  { id: 'n62', italian: 'il tè', english: 'tea', type: 'noun', gender: 'masculine', example: 'Il tè è caldo.', exampleTranslation: 'The tea is hot.' },
  { id: 'n63', italian: 'il succo', english: 'juice', type: 'noun', gender: 'masculine', example: 'Mi piace il succo d\'arancia.', exampleTranslation: 'I like orange juice.' },
  { id: 'n64', italian: 'il dolce', english: 'cake / sweet', type: 'noun', gender: 'masculine', example: 'Mangio il dolce dopo cena.', exampleTranslation: 'I eat cake after dinner.' },
  { id: 'n65', italian: 'il gelato', english: 'ice cream', type: 'noun', gender: 'masculine', example: 'Il gelato è freddo e delizioso.', exampleTranslation: 'Ice cream is cold and delicious.' },
  { id: 'n66', italian: 'il vestito', english: 'dress / suit', type: 'noun', gender: 'masculine', example: 'Indosso un vestito nuovo.', exampleTranslation: 'I am wearing a new dress.' },
  { id: 'n67', italian: 'la camicia', english: 'shirt', type: 'noun', gender: 'feminine', example: 'La camicia è azzurra.', exampleTranslation: 'The shirt is blue.' },
  { id: 'n68', italian: 'i pantaloni', english: 'pants', type: 'noun', gender: 'masculine', example: 'I pantaloni sono neri.', exampleTranslation: 'The pants are black.' },
  { id: 'n69', italian: 'la gonna', english: 'skirt', type: 'noun', gender: 'feminine', example: 'La gonna è rossa.', exampleTranslation: 'The skirt is red.' },
  { id: 'n70', italian: 'la scarpa', english: 'shoe', type: 'noun', gender: 'feminine', example: 'La scarpa è comoda.', exampleTranslation: 'The shoe is comfortable.' },
  { id: 'n71', italian: 'il cappello', english: 'hat', type: 'noun', gender: 'masculine', example: 'Indosso un cappello in estate.', exampleTranslation: 'I wear a hat in summer.' },
  { id: 'n72', italian: 'il guanto', english: 'glove', type: 'noun', gender: 'masculine', example: 'I guanti sono di lana.', exampleTranslation: 'The gloves are wool.' },
  { id: 'n73', italian: 'la sciarpa', english: 'scarf', type: 'noun', gender: 'feminine', example: 'La sciarpa è calda.', exampleTranslation: 'The scarf is warm.' },
  { id: 'n74', italian: 'il cappotto', english: 'coat', type: 'noun', gender: 'masculine', example: 'Il cappotto è pesante.', exampleTranslation: 'The coat is heavy.' },
  { id: 'n75', italian: 'l\'orologio', english: 'clock / watch', type: 'noun', gender: 'masculine', example: 'Che ore sono? Guardo l\'orologio.', exampleTranslation: 'What time is it? I look at the watch.' },
  { id: 'n76', italian: 'il libro', english: 'book', type: 'noun', gender: 'masculine', example: 'Leggo un libro interessante.', exampleTranslation: 'I read an interesting book.' },
  { id: 'n77', italian: 'il quaderno', english: 'notebook', type: 'noun', gender: 'masculine', example: 'Scrivo nel quaderno.', exampleTranslation: 'I write in the notebook.' },
  { id: 'n78', italian: 'la penna', english: 'pen', type: 'noun', gender: 'feminine', example: 'La penna è nera.', exampleTranslation: 'The pen is black.' },
  { id: 'n79', italian: 'la matita', english: 'pencil', type: 'noun', gender: 'feminine', example: 'Scrivo con la matita.', exampleTranslation: 'I write with a pencil.' },
  { id: 'n80', italian: 'il foglio', english: 'sheet / paper', type: 'noun', gender: 'masculine', example: 'Scrivo su un foglio di carta.', exampleTranslation: 'I write on a sheet of paper.' },
  { id: 'n81', italian: 'la tavola', english: 'table', type: 'noun', gender: 'feminine', example: 'Mi siedo alla tavola.', exampleTranslation: 'I sit at the table.' },
  { id: 'n82', italian: 'il sofà', english: 'sofa', type: 'noun', gender: 'masculine', example: 'Mi relasso sul sofà.', exampleTranslation: 'I relax on the sofa.' },
  { id: 'n83', italian: 'l\'armadio', english: 'wardrobe / closet', type: 'noun', gender: 'masculine', example: 'I vestiti sono nell\'armadio.', exampleTranslation: 'The clothes are in the closet.' },
  { id: 'n84', italian: 'il cuscino', english: 'pillow', type: 'noun', gender: 'masculine', example: 'Il cuscino è morbido.', exampleTranslation: 'The pillow is soft.' },
  { id: 'n85', italian: 'la coperta', english: 'blanket', type: 'noun', gender: 'feminine', example: 'La coperta è calda.', exampleTranslation: 'The blanket is warm.' },
  { id: 'n86', italian: 'lo specchio', english: 'mirror', type: 'noun', gender: 'masculine', example: 'Mi guardo nello specchio.', exampleTranslation: 'I look at myself in the mirror.' },
  { id: 'n87', italian: 'il quadro', english: 'painting', type: 'noun', gender: 'masculine', example: 'Il quadro è bellissimo.', exampleTranslation: 'The painting is very beautiful.' },
  { id: 'n88', italian: 'la lampada', english: 'lamp', type: 'noun', gender: 'feminine', example: 'La lampada illumina la stanza.', exampleTranslation: 'The lamp lights up the room.' },
  { id: 'n89', italian: 'la porta', english: 'door', type: 'noun', gender: 'feminine', example: 'Apri la porta, per favore.', exampleTranslation: 'Open the door, please.' },
  { id: 'n90', italian: 'il tetto', english: 'roof', type: 'noun', gender: 'masculine', example: 'Il tetto è rosso.', exampleTranslation: 'The roof is red.' },

  // Verbs (infinitive forms for flashcards)
  { id: 'v1', italian: 'parlare', english: 'to speak', type: 'verb', example: 'Parlo italiano ogni giorno.', exampleTranslation: 'I speak Italian every day.' },
  { id: 'v2', italian: 'mangiare', english: 'to eat', type: 'verb', example: 'Mangio la pasta a pranzo.', exampleTranslation: 'I eat pasta at lunch.' },
  { id: 'v3', italian: 'dormire', english: 'to sleep', type: 'verb', example: 'Dormo otto ore ogni notte.', exampleTranslation: 'I sleep eight hours every night.' },
  { id: 'v4', italian: 'leggere', english: 'to read', type: 'verb', example: 'Leggo un libro la sera.', exampleTranslation: 'I read a book in the evening.' },
  { id: 'v5', italian: 'scrivere', english: 'to write', type: 'verb', example: 'Scrivo una letter all\'amico.', exampleTranslation: 'I write a letter to a friend.' },
  { id: 'v6', italian: 'camminare', english: 'to walk', type: 'verb', example: 'Cammino nel parco ogni mattina.', exampleTranslation: 'I walk in the park every morning.' },
  { id: 'v7', italian: 'essere', english: 'to be', type: 'verb', example: 'Io sono italiano.', exampleTranslation: 'I am Italian.' },
  { id: 'v8', italian: 'avere', english: 'to have', type: 'verb', example: 'Ho una macchina nuova.', exampleTranslation: 'I have a new car.' },
  { id: 'v9', italian: 'andare', english: 'to go', type: 'verb', example: 'Vado al mercato domani.', exampleTranslation: 'I am going to the market tomorrow.' },
  { id: 'v10', italian: 'fare', english: 'to do / to make', type: 'verb', example: 'Faccio colazione alle sette.', exampleTranslation: 'I have breakfast at seven.' },
  { id: 'v11', italian: 'venire', english: 'to come', type: 'verb', example: 'Vengo a casa tua stasera.', exampleTranslation: 'I am coming to your house tonight.' },
  { id: 'v12', italian: 'vedere', english: 'to see', type: 'verb', example: 'Vedo il tramonto dal balcone.', exampleTranslation: 'I see the sunset from the balcony.' },
  { id: 'v13', italian: 'sapere', english: 'to know (a fact)', type: 'verb', example: 'So dove si trova la stazione.', exampleTranslation: 'I know where the station is.' },
  { id: 'v14', italian: 'volere', english: 'to want', type: 'verb', example: 'Voglio imparare l\'italiano.', exampleTranslation: 'I want to learn Italian.' },
  { id: 'v15', italian: 'potere', english: 'to be able to / can', type: 'verb', example: 'Posso aiutarti domani.', exampleTranslation: 'I can help you tomorrow.' },
  { id: 'v16', italian: 'prendere', english: 'to take', type: 'verb', example: 'Prendo il caffè senza zucchero.', exampleTranslation: 'I take my coffee without sugar.' },
  { id: 'v17', italian: 'sentire', english: 'to hear / to feel', type: 'verb', example: 'Sento un rumore strano.', exampleTranslation: 'I hear a strange noise.' },
  { id: 'v18', italian: 'uscire', english: 'to go out', type: 'verb', example: 'Esco con gli amici sabato.', exampleTranslation: 'I go out with friends on Saturday.' },
  { id: 'v19', italian: 'pensare', english: 'to think', type: 'verb', example: 'Penso spesso al futuro.', exampleTranslation: 'I often think about the future.' },
  { id: 'v20', italian: 'trovare_v', italian_alias: 'trovare', english: 'to find', type: 'verb', example: 'Trovo sempre le chiavi.', exampleTranslation: 'I always find my keys.' },
  { id: 'v21', italian: 'comprare', english: 'to buy', type: 'verb', example: 'Devo comprare il pane.', exampleTranslation: 'I need to buy bread.' },
  { id: 'v22', italian: 'cercare_v', italian_alias: 'cercare', english: 'to look for', type: 'verb', example: 'Cerco i miei occhiali.', exampleTranslation: 'I am looking for my glasses.' },
  { id: 'v23', italian: 'aspettare', english: 'to wait', type: 'verb', example: 'Aspetto l\'autobus.', exampleTranslation: 'I am waiting for the bus.' },
  { id: 'v24', italian: 'chiamare', english: 'to call', type: 'verb', example: 'Ti chiamo più tardi.', exampleTranslation: 'I will call you later.' },
  { id: 'v25', italian: 'portare', english: 'to bring / to carry', type: 'verb', example: 'Porto io le valigie.', exampleTranslation: 'I will carry the suitcases.' },
  { id: 'v26', italian: 'dare', english: 'to give', type: 'verb', example: 'Ti do il mio numero.', exampleTranslation: 'I give you my number.' },
  { id: 'v27', italian: 'dire_v', italian_alias: 'dire', english: 'to say / to tell', type: 'verb', example: 'Cosa dici?', exampleTranslation: 'What are you saying?' },
  { id: 'v32', italian: 'credere', english: 'to believe', type: 'verb', example: 'Credo che sia vero.', exampleTranslation: 'I believe it is true.' },
  { id: 'v33', italian: 'vivere', english: 'to live', type: 'verb', example: 'Vivo in Italia.', exampleTranslation: 'I live in Italy.' },
  { id: 'v34', italian: 'aprire', english: 'to open', type: 'verb', example: 'Apri la porta.', exampleTranslation: 'Open the door.' },
  { id: 'v35', italian: 'chiudere', english: 'to close', type: 'verb', example: 'Chiudi la finestra.', exampleTranslation: 'Close the window.' },
  { id: 'v37', italian: 'morire', english: 'to die', type: 'verb', example: 'Il fiore muore.', exampleTranslation: 'The flower is dying.' },
  { id: 'v38', italian: 'nascere', english: 'to be born', type: 'verb', example: 'Sono nato a Roma.', exampleTranslation: 'I was born in Rome.' },
  { id: 'v39', italian: 'diventare', english: 'to become', type: 'verb', example: 'Voglio diventare bravo.', exampleTranslation: 'I want to become good.' },
  { id: 'v40', italian: 'restare', english: 'to remain / to stay', type: 'verb', example: 'Resto a casa.', exampleTranslation: 'I am staying home.' },
  { id: 'v41', italian: 'ascoltare', english: 'to listen', type: 'verb', example: 'Ascolto la musica.', exampleTranslation: 'I listen to music.' },
  { id: 'v42', italian: 'guardare', english: 'to look / to watch', type: 'verb', example: 'Guardo la TV.', exampleTranslation: 'I watch TV.' },
  { id: 'v43', italian: 'vincere', english: 'to win', type: 'verb', example: 'Voglio vincere.', exampleTranslation: 'I want to win.' },
  { id: 'v44', italian: 'perdere', english: 'to lose', type: 'verb', example: 'Non mi piace perdere.', exampleTranslation: 'I don\'t like to lose.' },
  { id: 'v45', italian: 'pagare', english: 'to pay', type: 'verb', example: 'Pago io.', exampleTranslation: 'I\'ll pay.' },
  { id: 'v46', italian: 'vendere', english: 'to sell', type: 'verb', example: 'Vendo la mia bici.', exampleTranslation: 'I am selling my bike.' },
  { id: 'v47', italian: 'correre', english: 'to run', type: 'verb', example: 'Corro ogni mattina.', exampleTranslation: 'I run every morning.' },
  { id: 'v49', italian: 'chiedere', english: 'to ask', type: 'verb', example: 'Chiedo un favore.', exampleTranslation: 'I ask for a favor.' },
  { id: 'v50', italian: 'rispondere', english: 'to answer', type: 'verb', example: 'Rispondo alla mail.', exampleTranslation: 'I answer the email.' },
  { id: 'v51', italian: 'finire', english: 'to finish', type: 'verb', example: 'Finisco il lavoro.', exampleTranslation: 'I finish the work.' },
  { id: 'v52', italian: 'iniziare', english: 'to begin', type: 'verb', example: 'Inizio domani.', exampleTranslation: 'I start tomorrow.' },
  { id: 'v53', italian: 'giocare', english: 'to play', type: 'verb', example: 'Gioco a calcio.', exampleTranslation: 'I play soccer.' },
  { id: 'v54', italian: 'studiare', english: 'to study', type: 'verb', example: 'Studio italiano.', exampleTranslation: 'I study Italian.' },
  { id: 'v55', italian: 'lavorare', english: 'to work', type: 'verb', example: 'Lavoro molto.', exampleTranslation: 'I work a lot.' },
  { id: 'v56', italian: 'viaggiare', english: 'to travel', type: 'verb', example: 'Viaggio spesso.', exampleTranslation: 'I travel often.' },
  { id: 'v57', italian: 'entrare', english: 'to enter', type: 'verb', example: 'Entro nella stanza.', exampleTranslation: 'I enter the room.' },
  { id: 'v59', italian: 'salire', english: 'to go up', type: 'verb', example: 'Salgo le scale.', exampleTranslation: 'I go up the stairs.' },
  { id: 'v60', italian: 'scendere', english: 'to go down', type: 'verb', example: 'Scendo dal treno.', exampleTranslation: 'I get off the train.' },
  { id: 'v62', italian: 'usare', english: 'to use', type: 'verb', example: 'Uso il telefono.', exampleTranslation: 'I use the phone.' },
  { id: 'v63', italian: 'cambiare', english: 'to change', type: 'verb', example: 'Cambio idea.', exampleTranslation: 'I change my mind.' },
  { id: 'v64', italian: 'lasciare', english: 'to leave', type: 'verb', example: 'Lascio la casa.', exampleTranslation: 'I leave the house.' },
  { id: 'v65', italian: 'guidare', english: 'to drive', type: 'verb', example: 'Guido la macchina.', exampleTranslation: 'I drive the car.' },
  { id: 'v66', italian: 'amare', english: 'to love', type: 'verb', example: 'Amo la musica.', exampleTranslation: 'I love music.' },
  { id: 'v67', italian: 'odiare', english: 'to hate', type: 'verb', example: 'Odio aspettare.', exampleTranslation: 'I hate waiting.' },
  { id: 'v68', italian: 'offrire', english: 'to offer', type: 'verb', example: 'Offro un caffè.', exampleTranslation: 'I offer a coffee.' },
  { id: 'v69', italian: 'preparare', english: 'to prepare', type: 'verb', example: 'Preparo la cena.', exampleTranslation: 'I prepare dinner.' },
  { id: 'v70', italian: 'spendere', english: 'to spend', type: 'verb', example: 'Spendo troppo.', exampleTranslation: 'I spend too much.' },
  { id: 'v71', italian: 'ricevere', english: 'to receive', type: 'verb', example: 'Ricevo una lettera.', exampleTranslation: 'I receive a letter.' },
  { id: 'v72', italian: 'imparare', english: 'to learn', type: 'verb', example: 'Imparo velocemente.', exampleTranslation: 'I learn quickly.' },
  { id: 'v73', italian: 'ricordare', english: 'to remember', type: 'verb', example: 'Ricordo tutto.', exampleTranslation: 'I remember everything.' },
  { id: 'v74', italian: 'dimenticare', english: 'to forget', type: 'verb', example: 'Dimentico il nome.', exampleTranslation: 'I forget the name.' },
  { id: 'v75', italian: 'scegliere', english: 'to choose', type: 'verb', example: 'Scelgo questo.', exampleTranslation: 'I choose this.' },
  { id: 'v76', italian: 'sedere', english: 'to sit', type: 'verb', example: 'Siedo qui.', exampleTranslation: 'I sit here.' },
  { id: 'v77', italian: 'alzare', english: 'to raise', type: 'verb', example: 'Alzo la mano.', exampleTranslation: 'I raise my hand.' },
  { id: 'v78', italian: 'spegnere', english: 'to turn off', type: 'verb', example: 'Spengo la luce.', exampleTranslation: 'I turn off the light.' },
  { id: 'v79', italian: 'accendere', english: 'to turn on', type: 'verb', example: 'Accendo la TV.', exampleTranslation: 'I turn on the TV.' },
  { id: 'v80', italian: 'servire', english: 'to serve / need', type: 'verb', example: 'Mi serve aiuto.', exampleTranslation: 'I need help.' },
  { id: 'v81', italian: 'telefonare', english: 'to call (phone)', type: 'verb', example: 'Telefono a Maria.', exampleTranslation: 'I call Maria.' },
  { id: 'v82', italian: 'mandare', english: 'to send', type: 'verb', example: 'Mando un messaggio.', exampleTranslation: 'I send a message.' },
  { id: 'v83', italian: 'costare', english: 'to cost', type: 'verb', example: 'Costa troppo.', exampleTranslation: 'It costs too much.' },
  { id: 'v84', italian: 'rimanere', english: 'to remain', type: 'verb', example: 'Rimango qui.', exampleTranslation: 'I remain here.' },
  { id: 'v85', italian: 'piacere', english: 'to like', type: 'verb', example: 'Mi piace il vino.', exampleTranslation: 'I like wine.' },
  { id: 'v87', italian: 'tenere', english: 'to hold', type: 'verb', example: 'Tengo il libro.', exampleTranslation: 'I hold the book.' },
  { id: 'v88', italian: 'incontrare', english: 'to meet', type: 'verb', example: 'Incontro un amico.', exampleTranslation: 'I meet a friend.' },
  { id: 'v89', italian: 'passare', english: 'to pass / spend time', type: 'verb', example: 'Passo il tempo qui.', exampleTranslation: 'I spend time here.' },
  { id: 'v90', italian: 'aiutare', english: 'to help', type: 'verb', example: 'Aiuto mia madre.', exampleTranslation: 'I help my mother.' },

  // Adjectives
  { id: 'a1', italian: 'bello / bella', english: 'beautiful / handsome', type: 'adjective', example: 'Che bella giornata!', exampleTranslation: 'What a beautiful day!' },
  { id: 'a2', italian: 'grande', english: 'big / large / great', type: 'adjective', example: 'Ho una casa grande.', exampleTranslation: 'I have a large house.' },
  { id: 'a3', italian: 'piccolo / piccola', english: 'small / little', type: 'adjective', example: 'Ho un appartamento piccolo.', exampleTranslation: 'I have a small apartment.' },
  { id: 'a4', italian: 'buono / buona', english: 'good', type: 'adjective', example: 'Questo è un buon ristorante.', exampleTranslation: 'This is a good restaurant.' },
  { id: 'a5', italian: 'nuovo / nuova', english: 'new', type: 'adjective', example: 'Ho comprato una macchina nuova.', exampleTranslation: 'I bought a new car.' },
  { id: 'a6', italian: 'vecchio / vecchia', english: 'old', type: 'adjective', example: 'Questo è un edificio molto vecchio.', exampleTranslation: 'This is a very old building.' },
  { id: 'a7', italian: 'caldo / calda', english: 'hot / warm', type: 'adjective', example: 'Fa molto caldo oggi.', exampleTranslation: 'It is very hot today.' },
  { id: 'a8', italian: 'freddo / fredda', english: 'cold', type: 'adjective', example: 'L\'acqua è fredda.', exampleTranslation: 'The water is cold.' },
  { id: 'a9', italian: 'felice', english: 'happy', type: 'adjective', example: 'Sono molto felice oggi.', exampleTranslation: 'I am very happy today.' },
  { id: 'a10', italian: 'triste', english: 'sad', type: 'adjective', example: 'Mi sento triste senza di te.', exampleTranslation: 'I feel sad without you.' },
  { id: 'a11', italian: 'interessante', english: 'interesting', type: 'adjective', example: 'Questo libro è molto interessante.', exampleTranslation: 'This book is very interesting.' },
  { id: 'a12', italian: 'difficile', english: 'difficult / hard', type: 'adjective', example: 'L\'italiano è difficile ma bellissimo.', exampleTranslation: 'Italian is difficult but beautiful.' },
  { id: 'a13', italian: 'facile', english: 'easy', type: 'adjective', example: 'Questo esercizio è facile.', exampleTranslation: 'This exercise is easy.' },
  { id: 'a14', italian: 'lungo / lunga', english: 'long', type: 'adjective', example: 'Ho fatto un lungo viaggio.', exampleTranslation: 'I took a long journey.' },
  { id: 'a15', italian: 'breve', english: 'short / brief', type: 'adjective', example: 'La lezione è stata breve.', exampleTranslation: 'The lesson was short.' },
  { id: 'a16', italian: 'veloce', english: 'fast / quick', type: 'adjective', example: 'La macchina è molto veloce.', exampleTranslation: 'The car is very fast.' },
  { id: 'a17', italian: 'lento / lenta', english: 'slow', type: 'adjective', example: 'Il treno è lento oggi.', exampleTranslation: 'The train is slow today.' },
  { id: 'a18', italian: 'giovane', english: 'young', type: 'adjective', example: 'Sei ancora giovane.', exampleTranslation: 'You are still young.' },
  { id: 'a19', italian: 'ricco / ricca', english: 'rich', type: 'adjective', example: 'Non sono un uomo ricco.', exampleTranslation: 'I am not a rich man.' },
  { id: 'a20', italian: 'povero / povera', english: 'poor', type: 'adjective', example: 'Il paese è povero.', exampleTranslation: 'The village is poor.' },
  { id: 'a21', italian: 'forte', english: 'strong', type: 'adjective', example: 'Sei molto forte.', exampleTranslation: 'You are very strong.' },
  { id: 'a22', italian: 'debole', english: 'weak', type: 'adjective', example: 'Mi sento debole oggi.', exampleTranslation: 'I feel weak today.' },
  { id: 'a23', italian: 'intelligente', english: 'intelligent', type: 'adjective', example: 'Sei una persona intelligente.', exampleTranslation: 'You are an intelligent person.' },
  { id: 'a24', italian: 'simpatico / simpatica', english: 'nice / likable', type: 'adjective', example: 'Il tuo amico è simpatico.', exampleTranslation: 'Your friend is nice.' },
  { id: 'a25', italian: 'antipatico / antipatica', english: 'unpleasant / mean', type: 'adjective', example: 'Quella persona è antipatica.', exampleTranslation: 'That person is unpleasant.' },
  { id: 'a26', italian: 'dolce', english: 'sweet', type: 'adjective', example: 'Il bambino è dolce.', exampleTranslation: 'The child is sweet.' },
  { id: 'a27', italian: 'amaro / amara', english: 'bitter', type: 'adjective', example: 'Il caffè è amaro.', exampleTranslation: 'The coffee is bitter.' },
  { id: 'a28', italian: 'salato / salata', english: 'salty', type: 'adjective', example: 'Il cibo è salato.', exampleTranslation: 'The food is salty.' },
  { id: 'a29', italian: 'acido / acida', english: 'sour / acidic', type: 'adjective', example: 'Il limone è acido.', exampleTranslation: 'The lemon is sour.' },
  { id: 'a30', italian: 'sporco / sporca', english: 'dirty', type: 'adjective', example: 'La stanza è sporca.', exampleTranslation: 'The room is dirty.' },
  { id: 'a31', italian: 'pulito / pulita', english: 'clean', type: 'adjective', example: 'La casa è pulita.', exampleTranslation: 'The house is clean.' },
  { id: 'a32', italian: 'umido / umida', english: 'humid / damp', type: 'adjective', example: 'L\'aria è umida.', exampleTranslation: 'The air is humid.' },
  { id: 'a33', italian: 'secco / secca', english: 'dry', type: 'adjective', example: 'Il pane è secco.', exampleTranslation: 'The bread is dry.' },
  { id: 'a34', italian: 'bagnato / bagnata', english: 'wet', type: 'adjective', example: 'I vestiti sono bagnati.', exampleTranslation: 'The clothes are wet.' },
  { id: 'a35', italian: 'morbido / morbida', english: 'soft', type: 'adjective', example: 'Il cuscino è morbido.', exampleTranslation: 'The pillow is soft.' },
  { id: 'a36', italian: 'duro / dura', english: 'hard', type: 'adjective', example: 'La roccia è dura.', exampleTranslation: 'The rock is hard.' },
  { id: 'a37', italian: 'leggero / leggera', english: 'light', type: 'adjective', example: 'La valigia è leggera.', exampleTranslation: 'The suitcase is light.' },
  { id: 'a38', italian: 'pesante', english: 'heavy', type: 'adjective', example: 'Il libro è pesante.', exampleTranslation: 'The book is heavy.' },
  { id: 'a39', italian: 'robusto / robusta', english: 'sturdy / robust', type: 'adjective', example: 'La tavola è robusta.', exampleTranslation: 'The table is sturdy.' },
  { id: 'a40', italian: 'fragile', english: 'fragile / delicate', type: 'adjective', example: 'Il vetro è fragile.', exampleTranslation: 'The glass is fragile.' },
  { id: 'a41', italian: 'luminoso / luminosa', english: 'bright / luminous', type: 'adjective', example: 'La stanza è luminosa.', exampleTranslation: 'The room is bright.' },
  { id: 'a42', italian: 'scuro / scura', english: 'dark', type: 'adjective', example: 'La notte è scura.', exampleTranslation: 'The night is dark.' },
  { id: 'a43', italian: 'chiaro / chiara', english: 'clear / light', type: 'adjective', example: 'L\'acqua è chiara.', exampleTranslation: 'The water is clear.' },
  { id: 'a44', italian: 'trasparente', english: 'transparent', type: 'adjective', example: 'Il vetro è trasparente.', exampleTranslation: 'The glass is transparent.' },
  { id: 'a45', italian: 'opaco / opaca', english: 'opaque', type: 'adjective', example: 'Il vetro opaco non è trasparente.', exampleTranslation: 'The opaque glass is not transparent.' },
  { id: 'a46', italian: 'lucido / lucida', english: 'shiny / glossy', type: 'adjective', example: 'Il tavolo è lucido.', exampleTranslation: 'The table is shiny.' },
  { id: 'a47', italian: 'opaco / opaca', english: 'dull / matte', type: 'adjective', example: 'La vernice opaca non brilla.', exampleTranslation: 'The dull paint does not shine.' },
  { id: 'a48', italian: 'colorato / colorata', english: 'colorful / colored', type: 'adjective', example: 'Il dipinto è molto colorato.', exampleTranslation: 'The painting is very colorful.' },
  { id: 'a49', italian: 'bianco / bianca', english: 'white', type: 'adjective', example: 'La neve è bianca.', exampleTranslation: 'The snow is white.' },
  { id: 'a50', italian: 'nero / nera', english: 'black', type: 'adjective', example: 'Il gatto è nero.', exampleTranslation: 'The cat is black.' },
  { id: 'a51', italian: 'rosso / rossa', english: 'red', type: 'adjective', example: 'La mela è rossa.', exampleTranslation: 'The apple is red.' },
  { id: 'a52', italian: 'blu / blu', english: 'blue', type: 'adjective', example: 'Il cielo è blu.', exampleTranslation: 'The sky is blue.' },
  { id: 'a53', italian: 'giallo / gialla', english: 'yellow', type: 'adjective', example: 'Il sole è giallo.', exampleTranslation: 'The sun is yellow.' },
  { id: 'a54', italian: 'verde', english: 'green', type: 'adjective', example: 'L\'erba è verde.', exampleTranslation: 'The grass is green.' },
  { id: 'a55', italian: 'arancione', english: 'orange', type: 'adjective', example: 'L\'arancia è arancione.', exampleTranslation: 'The orange is orange.' },
  { id: 'a56', italian: 'viola', english: 'purple', type: 'adjective', example: 'I fiori sono viola.', exampleTranslation: 'The flowers are purple.' },
  { id: 'a57', italian: 'rosa', english: 'pink', type: 'adjective', example: 'La camicia è rosa.', exampleTranslation: 'The shirt is pink.' },
  { id: 'a58', italian: 'grigio / grigia', english: 'gray', type: 'adjective', example: 'Il tempo è grigio.', exampleTranslation: 'The weather is gray.' },
  { id: 'a59', italian: 'marrone', english: 'brown', type: 'adjective', example: 'La scarpa è marrone.', exampleTranslation: 'The shoe is brown.' },
  { id: 'a60', italian: 'beige', english: 'beige', type: 'adjective', example: 'Il divano è beige.', exampleTranslation: 'The sofa is beige.' },
  { id: 'a61', italian: 'brillante', english: 'brilliant / bright', type: 'adjective', example: 'L\'idea è brillante.', exampleTranslation: 'The idea is brilliant.' },
  { id: 'a62', italian: 'stupido / stupida', english: 'stupid / dumb', type: 'adjective', example: 'Questo è stupido.', exampleTranslation: 'This is stupid.' },
  { id: 'a63', italian: 'colto / colta', english: 'cultured / educated', type: 'adjective', example: 'È una persona molto colta.', exampleTranslation: 'He is a very educated person.' },
  { id: 'a64', italian: 'incolto / incolta', english: 'uncultured / uneducated', type: 'adjective', example: 'Una persona incolta.', exampleTranslation: 'An uncultured person.' },
  { id: 'a65', italian: 'divertente', english: 'fun / amusing', type: 'adjective', example: 'Il film è molto divertente.', exampleTranslation: 'The movie is very fun.' },
  { id: 'a66', italian: 'noioso / noiosa', english: 'boring / tedious', type: 'adjective', example: 'Il libro è noioso.', exampleTranslation: 'The book is boring.' },
  { id: 'a67', italian: 'eccitante', english: 'exciting', type: 'adjective', example: 'La partita è eccitante.', exampleTranslation: 'The game is exciting.' },
  { id: 'a68', italian: 'stressante', english: 'stressful / stressing', type: 'adjective', example: 'Il lavoro è stressante.', exampleTranslation: 'The work is stressful.' },
  { id: 'a69', italian: 'calmante', english: 'calming', type: 'adjective', example: 'La musica è calmante.', exampleTranslation: 'The music is calming.' },
  { id: 'a70', italian: 'comodo / comoda', english: 'comfortable', type: 'adjective', example: 'Il divano è molto comodo.', exampleTranslation: 'The sofa is very comfortable.' },
  { id: 'a71', italian: 'scomodo / scomoda', english: 'uncomfortable', type: 'adjective', example: 'La sedia è scomoda.', exampleTranslation: 'The chair is uncomfortable.' },
  { id: 'a72', italian: 'pratico / pratica', english: 'practical', type: 'adjective', example: 'Una soluzione pratica.', exampleTranslation: 'A practical solution.' },
  { id: 'a73', italian: 'teorico / teorica', english: 'theoretical', type: 'adjective', example: 'Una discussione teorica.', exampleTranslation: 'A theoretical discussion.' },
  { id: 'a74', italian: 'astratto / astratta', english: 'abstract', type: 'adjective', example: 'L\'arte astratta è interessante.', exampleTranslation: 'Abstract art is interesting.' },
  { id: 'a75', italian: 'concreto / concreta', english: 'concrete / tangible', type: 'adjective', example: 'Hai una soluzione concreta?', exampleTranslation: 'Do you have a concrete solution?' },

  // Adverbs
  { id: 'ad1', italian: 'molto', english: 'very / much', type: 'adverb', example: 'Questo è molto bello.', exampleTranslation: 'This is very beautiful.' },
  { id: 'ad2', italian: 'poco', english: 'little / few', type: 'adverb', example: 'Dormo poco.', exampleTranslation: 'I sleep little.' },
  { id: 'ad3', italian: 'abbastanza', english: 'enough / quite', type: 'adverb', example: 'È abbastanza caldo.', exampleTranslation: 'It is quite hot.' },
  { id: 'ad4', italian: 'sempre', english: 'always', type: 'adverb', example: 'Sono sempre felice.', exampleTranslation: 'I am always happy.' },
  { id: 'ad5', italian: 'mai', english: 'never', type: 'adverb', example: 'Non mangio mai carne.', exampleTranslation: 'I never eat meat.' },
  { id: 'ad6', italian: 'spesso', english: 'often', type: 'adverb', example: 'Vado spesso al parco.', exampleTranslation: 'I often go to the park.' },
  { id: 'ad7', italian: 'raramente', english: 'rarely', type: 'adverb', example: 'Raramente mi arrabbio.', exampleTranslation: 'I rarely get angry.' },
  { id: 'ad8', italian: 'talvolta', english: 'sometimes', type: 'adverb', example: 'Talvolta penso al futuro.', exampleTranslation: 'Sometimes I think about the future.' },
  { id: 'ad9', italian: 'oggi', english: 'today', type: 'adverb', example: 'Oggi è una bella giornata.', exampleTranslation: 'Today is a beautiful day.' },
  { id: 'ad10', italian: 'ieri', english: 'yesterday', type: 'adverb', example: 'Ieri ho mangiato la pasta.', exampleTranslation: 'Yesterday I ate pasta.' },
  { id: 'ad11', italian: 'domani', english: 'tomorrow', type: 'adverb', example: 'Domani sarà una bella giornata.', exampleTranslation: 'Tomorrow will be a beautiful day.' },
  { id: 'ad12', italian: 'ora', english: 'now', type: 'adverb', example: 'Ora devo andare.', exampleTranslation: 'Now I have to go.' },
  { id: 'ad13', italian: 'qui', english: 'here', type: 'adverb', example: 'Qui è molto bello.', exampleTranslation: 'It is very beautiful here.' },
  { id: 'ad14', italian: 'lì', english: 'there', type: 'adverb', example: 'Lì abita mio amico.', exampleTranslation: 'My friend lives there.' },
  { id: 'ad15', italian: 'dove', english: 'where', type: 'adverb', example: 'Dove sei?', exampleTranslation: 'Where are you?' },
  { id: 'ad16', italian: 'quando', english: 'when', type: 'adverb', example: 'Quando arriverai?', exampleTranslation: 'When will you arrive?' },
  { id: 'ad17', italian: 'come', english: 'how', type: 'adverb', example: 'Come stai?', exampleTranslation: 'How are you?' },
  { id: 'ad18', italian: 'perché', english: 'why', type: 'adverb', example: 'Perché ridi?', exampleTranslation: 'Why are you laughing?' },
  { id: 'ad19', italian: 'piuttosto', english: 'rather / instead', type: 'adverb', example: 'Preferisco piuttosto il caffè.', exampleTranslation: 'I prefer coffee rather.' },
  { id: 'ad20', italian: 'subito', english: 'immediately / at once', type: 'adverb', example: 'Vengo subito.', exampleTranslation: 'I am coming right away.' },
  { id: 'ad21', italian: 'presto', english: 'early / soon', type: 'adverb', example: 'Arrivò presto al lavoro.', exampleTranslation: 'He arrived early at work.' },
  { id: 'ad22', italian: 'tardi', english: 'late', type: 'adverb', example: 'Mi sono svegliato tardi.', exampleTranslation: 'I woke up late.' },
  { id: 'ad23', italian: 'velocemente', english: 'quickly / fast', type: 'adverb', example: 'Corro velocemente.', exampleTranslation: 'I run quickly.' },
  { id: 'ad24', italian: 'lentamente', english: 'slowly', type: 'adverb', example: 'Cammina lentamente.', exampleTranslation: 'He walks slowly.' },
  { id: 'ad25', italian: 'facilmente', english: 'easily', type: 'adverb', example: 'Capisco facilmente.', exampleTranslation: 'I understand easily.' },
  { id: 'ad26', italian: 'difficilmente', english: 'hardly / with difficulty', type: 'adverb', example: 'Difficilmente mi trovo d\'accordo.', exampleTranslation: 'I hardly ever agree.' },
  { id: 'ad27', italian: 'certamente', english: 'certainly / surely', type: 'adverb', example: 'Certamente verrò.', exampleTranslation: 'I will certainly come.' },
  { id: 'ad28', italian: 'probabilmente', english: 'probably', type: 'adverb', example: 'Probabilmente pioverà domani.', exampleTranslation: 'It will probably rain tomorrow.' },
  { id: 'ad29', italian: 'forse', english: 'perhaps / maybe', type: 'adverb', example: 'Forse andrò al cinema.', exampleTranslation: 'Maybe I will go to the cinema.' },
  { id: 'ad30', italian: 'sì', english: 'yes', type: 'adverb', example: 'Sì, voglio venire.', exampleTranslation: 'Yes, I want to come.' },
  { id: 'ad31', italian: 'no', english: 'no', type: 'adverb', example: 'No, non posso.', exampleTranslation: 'No, I cannot.' },
  { id: 'ad32', italian: 'bene', english: 'well / good', type: 'adverb', example: 'Mi sento molto bene.', exampleTranslation: 'I feel very well.' },
  { id: 'ad33', italian: 'male', english: 'bad / poorly', type: 'adverb', example: 'Mi sento male oggi.', exampleTranslation: 'I feel bad today.' },
  { id: 'ad34', italian: 'così', english: 'so / like this', type: 'adverb', example: 'Non farmi così.', exampleTranslation: 'Don\'t do it like that.' },
  { id: 'ad35', italian: 'insieme', english: 'together', type: 'adverb', example: 'Andiamo insieme al cinema.', exampleTranslation: 'Let\'s go to the cinema together.' },
  { id: 'ad36', italian: 'solo', english: 'alone / only', type: 'adverb', example: 'Vado solo al lavoro.', exampleTranslation: 'I go to work alone.' },
  { id: 'ad37', italian: 'soprattutto', english: 'especially / above all', type: 'adverb', example: 'Mi piace soprattutto il cioccolato.', exampleTranslation: 'I especially like chocolate.' },
  { id: 'ad38', italian: 'inoltre', english: 'furthermore / besides', type: 'adverb', example: 'Inoltre, è molto caro.', exampleTranslation: 'Furthermore, it is very expensive.' },
  { id: 'ad39', italian: 'infine', english: 'finally', type: 'adverb', example: 'Infine, siamo arrivati a casa.', exampleTranslation: 'Finally, we arrived home.' },
  { id: 'ad40', italian: 'comunque', english: 'anyway / however', type: 'adverb', example: 'Comunque, grazie per l\'aiuto.', exampleTranslation: 'Anyway, thanks for the help.' },
  { id: 'ad41', italian: 'almeno', english: 'at least', type: 'adverb', example: 'Almeno hai provato.', exampleTranslation: 'At least you tried.' },
  { id: 'ad42', italian: 'davvero', english: 'really / truly', type: 'adverb', example: 'È davvero interessante.', exampleTranslation: 'It is really interesting.' },
  { id: 'ad43', italian: 'quasi', english: 'almost / nearly', type: 'adverb', example: 'È quasi mezzanotte.', exampleTranslation: 'It is almost midnight.' },
  { id: 'ad44', italian: 'finalmente', english: 'finally / at last', type: 'adverb', example: 'Finalmente siamo qui.', exampleTranslation: 'Finally we are here.' },
  { id: 'ad45', italian: 'naturalmente', english: 'naturally / of course', type: 'adverb', example: 'Naturalmente, verrò.', exampleTranslation: 'Of course, I will come.' },
  { id: 'ad46', italian: 'attentamente', english: 'carefully / attentively', type: 'adverb', example: 'Ascolto attentamente.', exampleTranslation: 'I listen carefully.' },
  { id: 'ad47', italian: 'silenziosamente', english: 'silently / quietly', type: 'adverb', example: 'Cammina silenziosamente.', exampleTranslation: 'He walks silently.' },
  { id: 'ad48', italian: 'felicemente', english: 'happily', type: 'adverb', example: 'Vivono felicemente.', exampleTranslation: 'They live happily.' },
  { id: 'ad49', italian: 'tristemente', english: 'sadly', type: 'adverb', example: 'Mi ha guardato tristemente.', exampleTranslation: 'He looked at me sadly.' },
  { id: 'ad50', italian: 'coraggiosamente', english: 'bravely / courageously', type: 'adverb', example: 'Ha agito coraggiosamente.', exampleTranslation: 'He acted bravely.' },
];

export const VERBS: Verb[] = [
  {
    id: 'essere',
    infinitive: 'essere',
    english: 'to be',
    type: 'irregular',
    auxiliary: 'essere',
    tenses: {
      presente: { io: 'sono', tu: 'sei', lui: 'è', noi: 'siamo', voi: 'siete', loro: 'sono' },
      passato_prossimo: { io: 'sono stato/a', tu: 'sei stato/a', lui: 'è stato/a', noi: 'siamo stati/e', voi: 'siete stati/e', loro: 'sono stati/e' },
      imperfetto: { io: 'ero', tu: 'eri', lui: 'era', noi: 'eravamo', voi: 'eravate', loro: 'erano' },
      futuro_semplice: { io: 'sarò', tu: 'sarai', lui: 'sarà', noi: 'saremo', voi: 'sarete', loro: 'saranno' },
      condizionale_presente: { io: 'sarei', tu: 'saresti', lui: 'sarebbe', noi: 'saremmo', voi: 'sareste', loro: 'sarebbero' },
      congiuntivo_presente: { io: 'sia', tu: 'sia', lui: 'sia', noi: 'siamo', voi: 'siate', loro: 'siano' },
      imperativo: { io: '-', tu: 'sii', lui: 'sia', noi: 'siamo', voi: 'siate', loro: 'siano' },
    },
  },
  {
    id: 'avere',
    infinitive: 'avere',
    english: 'to have',
    type: 'irregular',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'ho', tu: 'hai', lui: 'ha', noi: 'abbiamo', voi: 'avete', loro: 'hanno' },
      passato_prossimo: { io: 'ho avuto', tu: 'hai avuto', lui: 'ha avuto', noi: 'abbiamo avuto', voi: 'avete avuto', loro: 'hanno avuto' },
      imperfetto: { io: 'avevo', tu: 'avevi', lui: 'aveva', noi: 'avevamo', voi: 'avevate', loro: 'avevano' },
      futuro_semplice: { io: 'avrò', tu: 'avrai', lui: 'avrà', noi: 'avremo', voi: 'avrete', loro: 'avranno' },
      condizionale_presente: { io: 'avrei', tu: 'avresti', lui: 'avrebbe', noi: 'avremmo', voi: 'avreste', loro: 'avrebbero' },
      congiuntivo_presente: { io: 'abbia', tu: 'abbia', lui: 'abbia', noi: 'abbiamo', voi: 'abbiate', loro: 'abbiano' },
      imperativo: { io: '-', tu: 'abbi', lui: 'abbia', noi: 'abbiamo', voi: 'abbiate', loro: 'abbiano' },
    },
  },
  {
    id: 'andare',
    infinitive: 'andare',
    english: 'to go',
    type: 'irregular',
    auxiliary: 'essere',
    tenses: {
      presente: { io: 'vado', tu: 'vai', lui: 'va', noi: 'andiamo', voi: 'andate', loro: 'vanno' },
      passato_prossimo: { io: 'sono andato/a', tu: 'sei andato/a', lui: 'è andato/a', noi: 'siamo andati/e', voi: 'siete andati/e', loro: 'sono andati/e' },
      imperfetto: { io: 'andavo', tu: 'andavi', lui: 'andava', noi: 'andavamo', voi: 'andavate', loro: 'andavano' },
      futuro_semplice: { io: 'andrò', tu: 'andrai', lui: 'andrà', noi: 'andremo', voi: 'andrete', loro: 'andranno' },
      condizionale_presente: { io: 'andrei', tu: 'andresti', lui: 'andrebbe', noi: 'andremmo', voi: 'andreste', loro: 'andrebbero' },
      congiuntivo_presente: { io: 'vada', tu: 'vada', lui: 'vada', noi: 'andiamo', voi: 'andiate', loro: 'vadano' },
      imperativo: { io: '-', tu: 'va\'', lui: 'vada', noi: 'andiamo', voi: 'andate', loro: 'vadano' },
    },
  },
  {
    id: 'fare',
    infinitive: 'fare',
    english: 'to do / to make',
    type: 'irregular',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'faccio', tu: 'fai', lui: 'fa', noi: 'facciamo', voi: 'fate', loro: 'fanno' },
      passato_prossimo: { io: 'ho fatto', tu: 'hai fatto', lui: 'ha fatto', noi: 'abbiamo fatto', voi: 'avete fatto', loro: 'hanno fatto' },
      imperfetto: { io: 'facevo', tu: 'facevi', lui: 'faceva', noi: 'facevamo', voi: 'facevate', loro: 'facevano' },
      futuro_semplice: { io: 'farò', tu: 'farai', lui: 'farà', noi: 'faremo', voi: 'farete', loro: 'faranno' },
      condizionale_presente: { io: 'farei', tu: 'faresti', lui: 'farebbe', noi: 'faremmo', voi: 'fareste', loro: 'farebbero' },
      congiuntivo_presente: { io: 'faccia', tu: 'faccia', lui: 'faccia', noi: 'facciamo', voi: 'facciate', loro: 'facciano' },
      imperativo: { io: '-', tu: 'fa\'', lui: 'faccia', noi: 'facciamo', voi: 'fate', loro: 'facciano' },
    },
  },
  {
    id: 'bere',
    infinitive: 'bere',
    english: 'to drink',
    type: 'irregular',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'bevo', tu: 'bevi', lui: 'beve', noi: 'beviamo', voi: 'bevete', loro: 'bevono' },
      passato_prossimo: { io: 'ho bevuto', tu: 'hai bevuto', lui: 'ha bevuto', noi: 'abbiamo bevuto', voi: 'avete bevuto', loro: 'hanno bevuto' },
      imperfetto: { io: 'bevevo', tu: 'bevevi', lui: 'beveva', noi: 'bevevamo', voi: 'bevevate', loro: 'bevevano' },
      futuro_semplice: { io: 'berrò', tu: 'berrai', lui: 'berrà', noi: 'berremo', voi: 'berrete', loro: 'berranno' },
      condizionale_presente: { io: 'berrei', tu: 'berresti', lui: 'berrebbe', noi: 'berremmo', voi: 'berreste', loro: 'berrebbero' },
      congiuntivo_presente: { io: 'beva', tu: 'beva', lui: 'beva', noi: 'beviamo', voi: 'beviate', loro: 'bevano' },
      imperativo: { io: '-', tu: 'bevi', lui: 'beva', noi: 'beviamo', voi: 'bevete', loro: 'bevano' },
    },
  },
  {
    id: 'dare',
    infinitive: 'dare',
    english: 'to give',
    type: 'irregular',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'do', tu: 'dai', lui: 'dà', noi: 'diamo', voi: 'date', loro: 'danno' },
      passato_prossimo: { io: 'ho dato', tu: 'hai dato', lui: 'ha dato', noi: 'abbiamo dato', voi: 'avete dato', loro: 'hanno dato' },
      imperfetto: { io: 'davo', tu: 'davi', lui: 'dava', noi: 'davamo', voi: 'davate', loro: 'davano' },
      futuro_semplice: { io: 'darò', tu: 'darai', lui: 'darà', noi: 'daremo', voi: 'darete', loro: 'daranno' },
      condizionale_presente: { io: 'darei', tu: 'daresti', lui: 'darebbe', noi: 'daremmo', voi: 'dareste', loro: 'darebbero' },
      congiuntivo_presente: { io: 'dia', tu: 'dia', lui: 'dia', noi: 'diamo', voi: 'diate', loro: 'diano' },
      imperativo: { io: '-', tu: 'da\'', lui: 'dia', noi: 'diamo', voi: 'date', loro: 'diano' },
    },
  },
  {
    id: 'dire',
    infinitive: 'dire',
    english: 'to say / to tell',
    type: 'irregular',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'dico', tu: 'dici', lui: 'dice', noi: 'diciamo', voi: 'dite', loro: 'dicono' },
      passato_prossimo: { io: 'ho detto', tu: 'hai detto', lui: 'ha detto', noi: 'abbiamo detto', voi: 'avete detto', loro: 'hanno detto' },
      imperfetto: { io: 'dicevo', tu: 'dicevi', lui: 'diceva', noi: 'dicevamo', voi: 'dicevate', loro: 'dicevano' },
      futuro_semplice: { io: 'dirò', tu: 'dirai', lui: 'dirà', noi: 'diremo', voi: 'direte', loro: 'diranno' },
      condizionale_presente: { io: 'direi', tu: 'diresti', lui: 'direbbe', noi: 'diremmo', voi: 'direste', loro: 'direbbero' },
      congiuntivo_presente: { io: 'dica', tu: 'dica', lui: 'dica', noi: 'diciamo', voi: 'diciate', loro: 'dicano' },
      imperativo: { io: '-', tu: 'di\'', lui: 'dica', noi: 'diciamo', voi: 'dite', loro: 'dicano' },
    },
  },
  {
    id: 'stare',
    infinitive: 'stare',
    english: 'to stay / to be',
    type: 'irregular',
    auxiliary: 'essere',
    tenses: {
      presente: { io: 'sto', tu: 'stai', lui: 'sta', noi: 'stiamo', voi: 'state', loro: 'stanno' },
      passato_prossimo: { io: 'sono stato/a', tu: 'sei stato/a', lui: 'è stato/a', noi: 'siamo stati/e', voi: 'siete stati/e', loro: 'sono stati/e' },
      imperfetto: { io: 'stavo', tu: 'stavi', lui: 'stava', noi: 'stavamo', voi: 'stavate', loro: 'stavano' },
      futuro_semplice: { io: 'starò', tu: 'starai', lui: 'starà', noi: 'staremo', voi: 'starete', loro: 'staranno' },
      condizionale_presente: { io: 'starei', tu: 'staresti', lui: 'starebbe', noi: 'staremmo', voi: 'stareste', loro: 'starebbero' },
      congiuntivo_presente: { io: 'stia', tu: 'stia', lui: 'stia', noi: 'stiamo', voi: 'stiate', loro: 'stiano' },
      imperativo: { io: '-', tu: 'sta\'', lui: 'stia', noi: 'stiamo', voi: 'state', loro: 'stiano' },
    },
  },
  {
    id: 'uscire',
    infinitive: 'uscire',
    english: 'to go out',
    type: 'irregular',
    auxiliary: 'essere',
    tenses: {
      presente: { io: 'esco', tu: 'esci', lui: 'esce', noi: 'usciamo', voi: 'uscite', loro: 'escono' },
      passato_prossimo: { io: 'sono uscito/a', tu: 'sei uscito/a', lui: 'è uscito/a', noi: 'siamo usciti/e', voi: 'siete usciti/e', loro: 'sono usciti/e' },
      imperfetto: { io: 'uscivo', tu: 'uscivi', lui: 'usciva', noi: 'uscivamo', voi: 'uscivate', loro: 'uscivano' },
      futuro_semplice: { io: 'uscirò', tu: 'uscirai', lui: 'uscirà', noi: 'usciremo', voi: 'uscirete', loro: 'usciranno' },
      condizionale_presente: { io: 'uscirei', tu: 'usciresti', lui: 'uscirebbe', noi: 'usciremmo', voi: 'uscireste', loro: 'uscirebbero' },
      congiuntivo_presente: { io: 'esca', tu: 'esca', lui: 'esca', noi: 'usciamo', voi: 'usciate', loro: 'escano' },
      imperativo: { io: '-', tu: 'esci', lui: 'esca', noi: 'usciamo', voi: 'uscite', loro: 'escano' },
    },
  },
  {
    id: 'venire',
    infinitive: 'venire',
    english: 'to come',
    type: 'irregular',
    auxiliary: 'essere',
    tenses: {
      presente: { io: 'vengo', tu: 'vieni', lui: 'viene', noi: 'veniamo', voi: 'venite', loro: 'vengono' },
      passato_prossimo: { io: 'sono venuto/a', tu: 'sei venuto/a', lui: 'è venuto/a', noi: 'siamo venuti/e', voi: 'siete venuti/e', loro: 'sono venuti/e' },
      imperfetto: { io: 'venivo', tu: 'venivi', lui: 'veniva', noi: 'venivamo', voi: 'venivate', loro: 'venivano' },
      futuro_semplice: { io: 'verrò', tu: 'verrai', lui: 'verrà', noi: 'verremo', voi: 'verrete', loro: 'verranno' },
      condizionale_presente: { io: 'verrei', tu: 'verresti', lui: 'verrebbe', noi: 'verremmo', voi: 'verreste', loro: 'verrebbero' },
      congiuntivo_presente: { io: 'venga', tu: 'venga', lui: 'venga', noi: 'veniamo', voi: 'veniate', loro: 'vengano' },
      imperativo: { io: '-', tu: 'vieni', lui: 'venga', noi: 'veniamo', voi: 'venite', loro: 'vengano' },
    },
  },
  {
    id: 'dovere',
    infinitive: 'dovere',
    english: 'to have to / must',
    type: 'irregular',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'devo', tu: 'devi', lui: 'deve', noi: 'dobbiamo', voi: 'dovete', loro: 'devono' },
      passato_prossimo: { io: 'ho dovuto', tu: 'hai dovuto', lui: 'ha dovuto', noi: 'abbiamo dovuto', voi: 'avete dovuto', loro: 'hanno dovuto' },
      imperfetto: { io: 'dovevo', tu: 'dovevi', lui: 'doveva', noi: 'dovevamo', voi: 'dovevate', loro: 'dovevano' },
      futuro_semplice: { io: 'dovrò', tu: 'dovrai', lui: 'dovrà', noi: 'dovremo', voi: 'dovrete', loro: 'dovranno' },
      condizionale_presente: { io: 'dovrei', tu: 'dovresti', lui: 'dovrebbe', noi: 'dovremmo', voi: 'dovreste', loro: 'dovrebbero' },
      congiuntivo_presente: { io: 'debba', tu: 'debba', lui: 'debba', noi: 'dobbiamo', voi: 'dobbiate', loro: 'debbano' },
      imperativo: { io: '-', tu: 'devi', lui: 'debba', noi: 'dobbiamo', voi: 'dobbiate', loro: 'debbano' },
    },
  },
  {
    id: 'potere',
    infinitive: 'potere',
    english: 'to be able to / can',
    type: 'irregular',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'posso', tu: 'puoi', lui: 'può', noi: 'possiamo', voi: 'potete', loro: 'possono' },
      passato_prossimo: { io: 'ho potuto', tu: 'hai potuto', lui: 'ha potuto', noi: 'abbiamo potuto', voi: 'avete potuto', loro: 'hanno potuto' },
      imperfetto: { io: 'potevo', tu: 'potevi', lui: 'poteva', noi: 'potevamo', voi: 'potevate', loro: 'potevano' },
      futuro_semplice: { io: 'potrò', tu: 'potrai', lui: 'potrà', noi: 'potremo', voi: 'potrete', loro: 'potranno' },
      condizionale_presente: { io: 'potrei', tu: 'potresti', lui: 'potrebbe', noi: 'potremmo', voi: 'potreste', loro: 'potrebbero' },
      congiuntivo_presente: { io: 'possa', tu: 'possa', lui: 'possa', noi: 'possiamo', voi: 'possiate', loro: 'possano' },
      imperativo: { io: '-', tu: '-', lui: 'possa', noi: 'possiamo', voi: 'possiate', loro: 'possano' },
    },
  },
  {
    id: 'volere',
    infinitive: 'volere',
    english: 'to want',
    type: 'irregular',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'voglio', tu: 'vuoi', lui: 'vuole', noi: 'vogliamo', voi: 'volete', loro: 'vogliono' },
      passato_prossimo: { io: 'ho voluto', tu: 'hai voluto', lui: 'ha voluto', noi: 'abbiamo voluto', voi: 'avete voluto', loro: 'hanno voluto' },
      imperfetto: { io: 'volevo', tu: 'volevi', lui: 'voleva', noi: 'volevamo', voi: 'volevate', loro: 'volevano' },
      futuro_semplice: { io: 'vorrò', tu: 'vorrai', lui: 'vorrà', noi: 'vorremo', voi: 'vorrete', loro: 'vorranno' },
      condizionale_presente: { io: 'vorrei', tu: 'vorresti', lui: 'vorrebbe', noi: 'vorremmo', voi: 'vorreste', loro: 'vorrebbero' },
      congiuntivo_presente: { io: 'voglia', tu: 'voglia', lui: 'voglia', noi: 'vogliamo', voi: 'vogliate', loro: 'vogliano' },
      imperativo: { io: '-', tu: 'vogli', lui: 'voglia', noi: 'vogliamo', voi: 'vogliate', loro: 'vogliano' },
    },
  },
  {
    id: 'sapere',
    infinitive: 'sapere',
    english: 'to know (a fact)',
    type: 'irregular',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'so', tu: 'sai', lui: 'sa', noi: 'sappiamo', voi: 'sapete', loro: 'sanno' },
      passato_prossimo: { io: 'ho saputo', tu: 'hai saputo', lui: 'ha saputo', noi: 'abbiamo saputo', voi: 'avete saputo', loro: 'hanno saputo' },
      imperfetto: { io: 'sapevo', tu: 'sapevi', lui: 'sapeva', noi: 'sapevamo', voi: 'sapevate', loro: 'sapevano' },
      futuro_semplice: { io: 'saprò', tu: 'saprai', lui: 'saprà', noi: 'sapremo', voi: 'saprete', loro: 'sapranno' },
      condizionale_presente: { io: 'saprei', tu: 'sapresti', lui: 'saprebbe', noi: 'sapremmo', voi: 'sapreste', loro: 'saprebbero' },
      congiuntivo_presente: { io: 'sappia', tu: 'sappia', lui: 'sappia', noi: 'sappiamo', voi: 'sappiate', loro: 'sappiano' },
      imperativo: { io: '-', tu: 'sappi', lui: 'sappia', noi: 'sappiamo', voi: 'sappiate', loro: 'sappiano' },
    },
  },
  {
    id: 'parlare',
    infinitive: 'parlare',
    english: 'to speak',
    type: 'regular-are',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'parlo', tu: 'parli', lui: 'parla', noi: 'parliamo', voi: 'parlate', loro: 'parlano' },
      passato_prossimo: { io: 'ho parlato', tu: 'hai parlato', lui: 'ha parlato', noi: 'abbiamo parlato', voi: 'avete parlato', loro: 'hanno parlato' },
      imperfetto: { io: 'parlavo', tu: 'parlavi', lui: 'parlava', noi: 'parlavamo', voi: 'parlavate', loro: 'parlavano' },
      futuro_semplice: { io: 'parlerò', tu: 'parlerai', lui: 'parlerà', noi: 'parleremo', voi: 'parlerete', loro: 'parleranno' },
      condizionale_presente: { io: 'parlerei', tu: 'parleresti', lui: 'parlerebbe', noi: 'parleremmo', voi: 'parlereste', loro: 'parlerebbero' },
      congiuntivo_presente: { io: 'parli', tu: 'parli', lui: 'parli', noi: 'parliamo', voi: 'parliate', loro: 'parlino' },
      imperativo: { io: '-', tu: 'parla', lui: 'parli', noi: 'parliamo', voi: 'parlate', loro: 'parlino' },
    },
  },
  {
    id: 'mangiare',
    infinitive: 'mangiare',
    english: 'to eat',
    type: 'regular-are',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'mangio', tu: 'mangi', lui: 'mangia', noi: 'mangiamo', voi: 'mangiate', loro: 'mangiano' },
      passato_prossimo: { io: 'ho mangiato', tu: 'hai mangiato', lui: 'ha mangiato', noi: 'abbiamo mangiato', voi: 'avete mangiato', loro: 'hanno mangiato' },
      imperfetto: { io: 'mangiavo', tu: 'mangiavi', lui: 'mangiava', noi: 'mangiavamo', voi: 'mangiavate', loro: 'mangiano' },
      futuro_semplice: { io: 'mangerò', tu: 'mangerai', lui: 'mangerà', noi: 'mangeremo', voi: 'mangerete', loro: 'mangeranno' },
      condizionale_presente: { io: 'mangerei', tu: 'mangeresti', lui: 'mangerebbe', noi: 'mangeremmo', voi: 'mangereste', loro: 'mangerebbero' },
      congiuntivo_presente: { io: 'mangi', tu: 'mangi', lui: 'mangi', noi: 'mangiamo', voi: 'mangiate', loro: 'mangino' },
      imperativo: { io: '-', tu: 'mangia', lui: 'mangi', noi: 'mangiamo', voi: 'mangiate', loro: 'mangino' },
    },
  },
  {
    id: 'prendere',
    infinitive: 'prendere',
    english: 'to take',
    type: 'regular-ere',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'prendo', tu: 'prendi', lui: 'prende', noi: 'prendiamo', voi: 'prendete', loro: 'prendono' },
      passato_prossimo: { io: 'ho preso', tu: 'hai preso', lui: 'ha preso', noi: 'abbiamo preso', voi: 'avete preso', loro: 'hanno preso' },
      imperfetto: { io: 'prendevo', tu: 'prendevi', lui: 'prendeva', noi: 'prendevamo', voi: 'prendevate', loro: 'prendevano' },
      futuro_semplice: { io: 'prenderò', tu: 'prenderai', lui: 'prenderà', noi: 'prenderemo', voi: 'prenderete', loro: 'prenderanno' },
      condizionale_presente: { io: 'prenderei', tu: 'prenderesti', lui: 'prenderebbe', noi: 'prendemmo', voi: 'prendeste', loro: 'prenderebbero' },
      congiuntivo_presente: { io: 'prenda', tu: 'prenda', lui: 'prenda', noi: 'prendiamo', voi: 'prendiate', loro: 'prendano' },
      imperativo: { io: '-', tu: 'prendi', lui: 'prenda', noi: 'prendiamo', voi: 'prendete', loro: 'prendano' },
    },
  },
  {
    id: 'leggere',
    infinitive: 'leggere',
    english: 'to read',
    type: 'regular-ere',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'leggo', tu: 'leggi', lui: 'legge', noi: 'leggiamo', voi: 'leggete', loro: 'leggono' },
      passato_prossimo: { io: 'ho letto', tu: 'hai letto', lui: 'ha letto', noi: 'abbiamo letto', voi: 'avete letto', loro: 'hanno letto' },
      imperfetto: { io: 'leggevo', tu: 'leggevi', lui: 'leggeva', noi: 'leggevamo', voi: 'leggevate', loro: 'leggevano' },
      futuro_semplice: { io: 'leggerò', tu: 'leggerai', lui: 'leggerà', noi: 'leggeremo', voi: 'leggerete', loro: 'leggeranno' },
      condizionale_presente: { io: 'leggerei', tu: 'leggeresti', lui: 'leggerebbe', noi: 'leggeremmo', voi: 'leggereste', loro: 'leggerebbero' },
      congiuntivo_presente: { io: 'legga', tu: 'legga', lui: 'legga', noi: 'leggiamo', voi: 'leggiate', loro: 'leggano' },
      imperativo: { io: '-', tu: 'leggi', lui: 'legga', noi: 'leggiamo', voi: 'leggete', loro: 'leggano' },
    },
  },
  {
    id: 'scrivere',
    infinitive: 'scrivere',
    english: 'to write',
    type: 'regular-ere',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'scrivo', tu: 'scrivi', lui: 'scrive', noi: 'scriviamo', voi: 'scrivete', loro: 'scrivono' },
      passato_prossimo: { io: 'ho scritto', tu: 'hai scritto', lui: 'ha scritto', noi: 'abbiamo scritto', voi: 'avete scritto', loro: 'hanno scritto' },
      imperfetto: { io: 'scrivevo', tu: 'scrivevi', lui: 'scriveva', noi: 'scrivevamo', voi: 'scrivevate', loro: 'scrivevano' },
      futuro_semplice: { io: 'scriverò', tu: 'scriverai', lui: 'scriverà', noi: 'scriveremo', voi: 'scriverete', loro: 'scriveranno' },
      condizionale_presente: { io: 'scriverei', tu: 'scriveresti', lui: 'scriverebbe', noi: 'scriveremmo', voi: 'scrivereste', loro: 'scriverebbero' },
      congiuntivo_presente: { io: 'scriva', tu: 'scriva', lui: 'scriva', noi: 'scriviamo', voi: 'scriviate', loro: 'scrivano' },
      imperativo: { io: '-', tu: 'scrivi', lui: 'scriva', noi: 'scriviamo', voi: 'scrivete', loro: 'scrivano' },
    },
  },
  {
    id: 'vedere',
    infinitive: 'vedere',
    english: 'to see',
    type: 'regular-ere',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'vedo', tu: 'vedi', lui: 'vede', noi: 'vediamo', voi: 'vedete', loro: 'vedono' },
      passato_prossimo: { io: 'ho visto', tu: 'hai visto', lui: 'ha visto', noi: 'abbiamo visto', voi: 'avete visto', loro: 'hanno visto' },
      imperfetto: { io: 'vedevo', tu: 'vedevi', lui: 'vedeva', noi: 'vedevamo', voi: 'vedevate', loro: 'vedevano' },
      futuro_semplice: { io: 'vedrò', tu: 'vedrai', lui: 'vedrà', noi: 'vedremo', voi: 'vedrete', loro: 'vedranno' },
      condizionale_presente: { io: 'vederei', tu: 'vederesti', lui: 'vedrebbe', noi: 'vedremmo', voi: 'vedereste', loro: 'vedrebbero' },
      congiuntivo_presente: { io: 'veda', tu: 'veda', lui: 'veda', noi: 'vediamo', voi: 'vediate', loro: 'vedano' },
      imperativo: { io: '-', tu: 'vedi', lui: 'veda', noi: 'vediamo', voi: 'vedete', loro: 'vedano' },
    },
  },
  {
    id: 'dormire',
    infinitive: 'dormire',
    english: 'to sleep',
    type: 'regular-ire',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'dormo', tu: 'dormi', lui: 'dorme', noi: 'dormiamo', voi: 'dormite', loro: 'dormono' },
      passato_prossimo: { io: 'ho dormito', tu: 'hai dormito', lui: 'ha dormito', noi: 'abbiamo dormito', voi: 'avete dormito', loro: 'hanno dormito' },
      imperfetto: { io: 'dormivo', tu: 'dormivi', lui: 'dormiva', noi: 'dormivamo', voi: 'dormivate', loro: 'dormivano' },
      futuro_semplice: { io: 'dormirò', tu: 'dormirai', lui: 'dormirà', noi: 'dormiremo', voi: 'dormirete', loro: 'dormiranno' },
      condizionale_presente: { io: 'dormirei', tu: 'dormiresti', lui: 'dormirebbe', noi: 'dormiremmo', voi: 'dormireste', loro: 'dormirebbero' },
      congiuntivo_presente: { io: 'dorma', tu: 'dorma', lui: 'dorma', noi: 'dormiamo', voi: 'dormiate', loro: 'dormano' },
      imperativo: { io: '-', tu: 'dormi', lui: 'dorma', noi: 'dormiamo', voi: 'dormite', loro: 'dormano' },
    },
  },
  {
    id: 'sentire',
    infinitive: 'sentire',
    english: 'to hear / to feel',
    type: 'regular-ire',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'sento', tu: 'senti', lui: 'sente', noi: 'sentiamo', voi: 'sentite', loro: 'sentono' },
      passato_prossimo: { io: 'ho sentito', tu: 'hai sentito', lui: 'ha sentito', noi: 'abbiamo sentito', voi: 'avete sentito', loro: 'hanno sentito' },
      imperfetto: { io: 'sentivo', tu: 'sentivi', lui: 'sentiva', noi: 'sentivamo', voi: 'sentivate', loro: 'sentivano' },
      futuro_semplice: { io: 'sentirò', tu: 'sentirai', lui: 'sentirà', noi: 'sentiremo', voi: 'sentirete', loro: 'sentiranno' },
      condizionale_presente: { io: 'sentirei', tu: 'sentiresti', lui: 'sentirebbe', noi: 'sentiremmo', voi: 'sentireste', loro: 'sentirebbero' },
      congiuntivo_presente: { io: 'senta', tu: 'senta', lui: 'senta', noi: 'sentiamo', voi: 'sentiate', loro: 'sentano' },
      imperativo: { io: '-', tu: 'senti', lui: 'senta', noi: 'sentiamo', voi: 'sentite', loro: 'sentano' },
    },
  },
  {
    id: 'capire',
    infinitive: 'capire',
    english: 'to understand',
    type: 'regular-ire',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'capisco', tu: 'capisci', lui: 'capisce', noi: 'capiamo', voi: 'capite', loro: 'capiscono' },
      passato_prossimo: { io: 'ho capito', tu: 'hai capito', lui: 'ha capito', noi: 'abbiamo capito', voi: 'avete capito', loro: 'hanno capito' },
      imperfetto: { io: 'capivo', tu: 'capivi', lui: 'capiva', noi: 'capivamo', voi: 'capivate', loro: 'capivano' },
      futuro_semplice: { io: 'capirò', tu: 'capirai', lui: 'capirà', noi: 'capiremo', voi: 'capirete', loro: 'capiranno' },
      condizionale_presente: { io: 'capirei', tu: 'capiresti', lui: 'capirebbe', noi: 'capiremmo', voi: 'capireste', loro: 'capirebbero' },
      congiuntivo_presente: { io: 'capisca', tu: 'capisca', lui: 'capisca', noi: 'capiamo', voi: 'capiate', loro: 'capiscano' },
      imperativo: { io: '-', tu: 'capisci', lui: 'capisca', noi: 'capiamo', voi: 'capite', loro: 'capiscano' },
    },
  },
  {
    id: 'cercare',
    infinitive: 'cercare',
    english: 'to look for',
    type: 'regular-are',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'cerco', tu: 'cerchi', lui: 'cerca', noi: 'cerchiamo', voi: 'cercate', loro: 'cercano' },
      passato_prossimo: { io: 'ho cercato', tu: 'hai cercato', lui: 'ha cercato', noi: 'abbiamo cercato', voi: 'avete cercato', loro: 'hanno cercato' },
      imperfetto: { io: 'cercavo', tu: 'cercavi', lui: 'cercava', noi: 'cercavamo', voi: 'cercavate', loro: 'cercavano' },
      futuro_semplice: { io: 'cercherò', tu: 'cercherai', lui: 'cercherà', noi: 'cercheremo', voi: 'cercherete', loro: 'cercheranno' },
      condizionale_presente: { io: 'cercherei', tu: 'cercheresti', lui: 'cercherebbe', noi: 'cercheremmo', voi: 'cerchereste', loro: 'cercherebbero' },
      congiuntivo_presente: { io: 'cerchi', tu: 'cerchi', lui: 'cerchi', noi: 'cerchiamo', voi: 'cerchiate', loro: 'cerchino' },
      imperativo: { io: '-', tu: 'cerca', lui: 'cerchi', noi: 'cerchiamo', voi: 'cercate', loro: 'cerchino' },
    },
  },
  {
    id: 'trovare',
    infinitive: 'trovare',
    english: 'to find',
    type: 'regular-are',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'trovo', tu: 'trovi', lui: 'trova', noi: 'troviamo', voi: 'trovate', loro: 'trovano' },
      passato_prossimo: { io: 'ho trovato', tu: 'hai trovato', lui: 'ha trovato', noi: 'abbiamo trovato', voi: 'avete trovato', loro: 'hanno trovato' },
      imperfetto: { io: 'trovavo', tu: 'trovavi', lui: 'trovava', noi: 'trovavamo', voi: 'trovavate', loro: 'trovano' },
      futuro_semplice: { io: 'troverò', tu: 'troverai', lui: 'troverà', noi: 'troveremo', voi: 'troverete', loro: 'troveranno' },
      condizionale_presente: { io: 'troverei', tu: 'troveresti', lui: 'troverebbe', noi: 'troveremmo', voi: 'trovereste', loro: 'troverebbero' },
      congiuntivo_presente: { io: 'trovi', tu: 'trovi', lui: 'trovi', noi: 'troviamo', voi: 'troviate', loro: 'trovino' },
      imperativo: { io: '-', tu: 'trova', lui: 'trovi', noi: 'troviamo', voi: 'trovate', loro: 'trovino' },
    },
  },
  {
    id: 'mettere',
    infinitive: 'mettere',
    english: 'to put',
    type: 'regular-ere',
    auxiliary: 'avere',
    tenses: {
      presente: { io: 'metto', tu: 'metti', lui: 'mette', noi: 'mettiamo', voi: 'mettete', loro: 'mettono' },
      passato_prossimo: { io: 'ho messo', tu: 'hai messo', lui: 'ha messo', noi: 'abbiamo messo', voi: 'avete messo', loro: 'hanno messo' },
      imperfetto: { io: 'mettevo', tu: 'mettevi', lui: 'metteva', noi: 'mettevamo', voi: 'mettevate', loro: 'mettevano' },
      futuro_semplice: { io: 'metterò', tu: 'metterai', lui: 'metterà', noi: 'metteremo', voi: 'metterete', loro: 'metteranno' },
      condizionale_presente: { io: 'metterei', tu: 'metteresti', lui: 'metterebbe', noi: 'metteremmo', voi: 'mettereste', loro: 'metterebbero' },
      congiuntivo_presente: { io: 'metta', tu: 'metta', lui: 'metta', noi: 'mettiamo', voi: 'mettiate', loro: 'mettano' },
      imperativo: { io: '-', tu: 'metti', lui: 'metta', noi: 'mettiamo', voi: 'mettete', loro: 'mettano' },
    },
  },
  {
    id: 'arrivare',
    infinitive: 'arrivare',
    english: 'to arrive',
    type: 'regular-are',
    auxiliary: 'essere',
    tenses: {
      presente: { io: 'arrivo', tu: 'arrivi', lui: 'arriva', noi: 'arriviamo', voi: 'arrivate', loro: 'arrivano' },
      passato_prossimo: { io: 'sono arrivato/a', tu: 'sei arrivato/a', lui: 'è arrivato/a', noi: 'siamo arrivati/e', voi: 'siete arrivati/e', loro: 'sono arrivati/e' },
      imperfetto: { io: 'arrivavo', tu: 'arrivavi', lui: 'arrivava', noi: 'arrivavamo', voi: 'arrivavate', loro: 'arrivavano' },
      futuro_semplice: { io: 'arriverò', tu: 'arriverai', lui: 'arriverà', noi: 'arriveremo', voi: 'arriverete', loro: 'arriveranno' },
      condizionale_presente: { io: 'arriverei', tu: 'arriveresti', lui: 'arriverebbe', noi: 'arriveremmo', voi: 'arrivereste', loro: 'arriverebbero' },
      congiuntivo_presente: { io: 'arrivi', tu: 'arrivi', lui: 'arrivi', noi: 'arriviamo', voi: 'arriviate', loro: 'arrivino' },
      imperativo: { io: '-', tu: 'arriva', lui: 'arrivi', noi: 'arriviamo', voi: 'arrivate', loro: 'arrivino' },
    },
  },
];

export const PRONOUNS = ['io', 'tu', 'lui', 'lei', 'noi', 'voi', 'loro'] as const;

export type Pronoun = typeof PRONOUNS[number];

export const PRONOUN_KEYS: Record<Pronoun, keyof Conjugation> = {
  'io': 'io',
  'tu': 'tu',
  'lui': 'lui',
  'lei': 'lui',
  'noi': 'noi',
  'voi': 'voi',
  'loro': 'loro',
};

export const TENSE_NAMES: Record<TenseId, string> = {
  presente: 'Presente',
  passato_prossimo: 'Passato Prossimo',
  imperfetto: 'Imperfetto',
  futuro_semplice: 'Futuro Semplice',
  condizionale_presente: 'Condizionale',
  congiuntivo_presente: 'Congiuntivo',
  imperativo: 'Imperativo',
};

export const TENSE_INFO: TenseInfo[] = [
  {
    id: 'presente',
    name: 'Present',
    italianName: 'Presente',
    when: 'Current actions, habitual actions, and universal truths.',
    examples: [
      { italian: 'Io parlo italiano.', english: 'I speak Italian.' },
      { italian: 'Lui mangia una mela.', english: 'He eats an apple.' },
      { italian: 'Noi viviamo in Italia.', english: 'We live in Italy.' },
    ],
    formation: 'Regular verbs follow the -are, -ere, -ire endings.',
  },
  {
    id: 'passato_prossimo',
    name: 'Past Perfect',
    italianName: 'Passato Prossimo',
    when: 'Recent past actions that have a connection to the present or were completed recently.',
    examples: [
      { italian: 'Ho mangiato una pizza.', english: 'I have eaten a pizza.' },
      { italian: 'Sono andato a Roma.', english: 'I went to Rome.' },
      { italian: 'Abbiamo finito il progetto.', english: 'We have finished the project.' },
    ],
    formation: 'Auxiliary (essere/avere) + Past Participle.',
  },
  {
    id: 'imperfetto',
    name: 'Imperfect',
    italianName: 'Imperfetto',
    when: 'Ongoing or repeated past actions, descriptions in the past, or background information.',
    examples: [
      { italian: 'Parlavo sempre con lui.', english: 'I used to talk to him all the time.' },
      { italian: 'Faceva freddo.', english: 'It was cold.' },
      { italian: 'Loro cantavano spesso.', english: 'They used to sing often.' },
    ],
    formation: 'Root + -avo, -evo, -ivo endings.',
  },
  {
    id: 'futuro_semplice',
    name: 'Simple Future',
    italianName: 'Futuro Semplice',
    when: 'Actions that will happen in the future.',
    examples: [
      { italian: 'Andrò in Italia l\'anno prossimo.', english: 'I will go to Italy next year.' },
      { italian: 'Mangeremo insieme domani.', english: 'We will eat together tomorrow.' },
      { italian: 'Loro parleranno italiano.', english: 'They will speak Italian.' },
    ],
    formation: 'Root + -rò, -rai, -rà endings.',
  },
  {
    id: 'condizionale_presente',
    name: 'Conditional',
    italianName: 'Condizionale',
    when: 'Actions that would happen under certain conditions.',
    examples: [
      { italian: 'Io leggerei il libro.', english: 'I would read the book.' },
      { italian: 'Mi piacerebbe visitare Italia.', english: 'I would like to visit Italy.' },
      { italian: 'Loro sarebbero felici.', english: 'They would be happy.' },
    ],
    formation: 'Root + -rei, -resti, -rebbe endings.',
  },
  {
    id: 'congiuntivo_presente',
    name: 'Subjunctive',
    italianName: 'Congiuntivo',
    when: 'Expressions of doubt, desire, possibility, or after certain verbs.',
    examples: [
      { italian: 'Credo che sia vero.', english: 'I believe it is true.' },
      { italian: 'Voglio che tu parli italiano.', english: 'I want you to speak Italian.' },
      { italian: 'È importante che studiamo.', english: 'It\'s important that we study.' },
    ],
    formation: 'Specific conjugations for each verb type and person.',
  },
  {
    id: 'imperativo',
    name: 'Imperative',
    italianName: 'Imperativo',
    when: 'Commands, requests, or orders.',
    examples: [
      { italian: 'Parla italiano!', english: 'Speak Italian!' },
      { italian: 'Leggi il libro.', english: 'Read the book.' },
      { italian: 'Ascoltiamo la musica.', english: 'Let\'s listen to music.' },
    ],
    formation: 'Special forms for tu, lui, noi, voi. No first person form.',
  },
];
